[project]
name = "complex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "numpy>=2.4.0",
    "torch>=2.9.1",
    "traci>=1.25.0",
    "uvicorn>=0.40.0",
]
