mode: "sumo_events"

simulation:
  sumo_config: "coldplay2/osm.sumocfg"
  simulation_speed: 0.1
  bounds:
    min_lat: 52.520
    max_lat: 52.531
    min_lon: 13.385
    max_lon: 13.405
  max_steps: 7200

model:
  hidden_layers: [64, 16]

fdrl:
  yellow_time: 3
  green_time: 30
system:
  server_host: localhost
  server_port: 12345
  max_roads: 5
  controlled_junctions:
    - "10215107459"
    - "10261850243"
    - "10941396748"
    - "10942351682"
    - "10944042503"
    - "10944046880"
    - "11024205351"
    - "11024205353"
    - "11055989392"
    - "11055989395"
    - "11055989397"
    - "11056005657"
    - "11056019968"
    - "11182735640"
    - "11182735641"
    - "1646118611"
    - "1646118614"
    - "2245082040"
    - "2245082071"
    - "2245082111"
    - "2245082117"
    - "2245082169"
    - "2245082282"
    - "2245082284"
    - "2245082297"
    - "2245082309"
    - "2245082319"
    - "2245082330"
    - "2245082337"
    - "2245082345"
    - "2245082350"
    - "2245082362"
    - "2245082395"
    - "2245082421"
    - "2245082429"
    - "2245082502"
    - "2245082504"
    - "2245082515"
    - "2245082518"
    - "2245082547"
    - "2245082550"
    - "2245082571"
    - "2245082580"
    - "2245082593"
    - "2245082596"
    - "2245082608"
    - "2245082626"
    - "2245082632"
    - "2245082669"
    - "2245082675"
    - "2245082686"
    - "2245082692"
    - "2245082715"
    - "2245082732"
    - "2245082742"
    - "2245082748"
    - "2245082750"
    - "2245082777"
    - "2245083071"
    - "2246310117"
    - "2246310122"
    - "344890457"
    - "344890541"
    - "344890542"
    - "4161412300"
    - "4161457092"
    - "4161457100"
    - "5458429287"
    - "6609081696"
    - "6609500419"
    - "6609500420"
    - "6609753291"
    - "6609753292"
    - "7365923716"
    - "7365923717"
    - "7365923719"
    - "7366702073"
    - "7366702075"
    - "7658543134"
    - "7658543142"
    - "7728961745"
    - "9171129215"
    - cluster_10006525751_4161457106
    - cluster_10261850246_2245082387
    - cluster_11056009669_11056009671
    - cluster_11072489262_4161412293
    - cluster_11182692495_7365923724
    - cluster_1646118610_5458429002
    - cluster_2245082187_4161412282
    - cluster_2245082210_5458428991
    - cluster_2245082219_2245082227
    - cluster_2245082244_2245082249
    - cluster_2245082332_5458428988
    - cluster_2245082368_2245082376
    - cluster_2245082393_2245082423_4233655598
    - cluster_2245082513_4161319752
    - cluster_344890761_6177994518
    - cluster_344890780_5458429001
    - cluster_4161457091_5458428998
  model_save_path: saved_models/universal_model.pth
  log_file: training_logs.json
  enable_patience: true
  patience_epochs: 20
  min_reward_delta: 0.05

sumo_rl_events:
  model_path: "./FDRL/saved_models"
  # Model trained on 6 junctions: state_dim = 6*2 = 12, action_dim = 6
  state_dim: 8
  action_dim: 4
