sumo:
  config_file: sumo_files/dy/osm.sumocfg
  step_length: 1.0
  gui: false
  gridlock_detection_time: 300.0
priority_weights:
  ambulance: 50.0
  bus: 10.0
  motorcycle: 1.0
  car: 1.0
fdrl:
  epochs: 50
  K: 500
  alpha: 0.05
  gamma: 0.99
  actor_lr: 0.0001
  critic_lr: 0.0005
  clip_epsilon: 0.2
  yellow_time: 3
  green_time: 10
model:
  hidden_layers:
  - 128
  - 64
  activation: relu
system:
  server_host: localhost
  server_port: 12345
  max_roads: 7
  controlled_junctions:
  - '10006525749'
  - '10172786319'
  - '10215107460'
  - '10261850243'
  - '10580905493'
  - '10765731567'
  - '10941396748'
  - '10942351673'
  - '10942351676'
  - '10942351679'
  - '10942351682'
  - '10944042503'
  - '10944046880'
  - '11024173961'
  - '11024173963'
  - '11024176120'
  - '11024205345'
  - '11024205346'
  - '11024205351'
  - '11024205353'
  - '11024335707'
  - '11024335709'
  - '11024471320'
  - '11024753525'
  - '11024786095'
  - '11024809111'
  - '11055960344'
  - '11055989392'
  - '11055989395'
  - '11055989397'
  - '11056005657'
  - '11056019968'
  - '11066825835'
  - '11066835723'
  - '11066868268'
  - '11066887358'
  - '11068775506'
  - '11068776520'
  - '11068791196'
  - '11068810952'
  - '11068861635'
  - '11068861641'
  - '11182735640'
  - '11182735641'
  - '11183067553'
  - '12167474243'
  - '13143907373'
  - '13283380595'
  - '13312982643'
  - '1646118614'
  - '2245082040'
  - '2245082071'
  - '2245082111'
  - '2245082117'
  - '2245082169'
  - '2245082282'
  - '2245082284'
  - '2245082297'
  - '2245082307'
  - '2245082309'
  - '2245082319'
  - '2245082330'
  - '2245082337'
  - '2245082345'
  - '2245082350'
  - '2245082362'
  - '2245082395'
  - '2245082421'
  - '2245082429'
  - '2245082502'
  - '2245082504'
  - '2245082515'
  - '2245082518'
  - '2245082547'
  - '2245082550'
  - '2245082571'
  - '2245082580'
  - '2245082593'
  - '2245082596'
  - '2245082608'
  - '2245082626'
  - '2245082632'
  - '2245082669'
  - '2245082675'
  - '2245082686'
  - '2245082692'
  - '2245082715'
  - '2245082732'
  - '2245082742'
  - '2245082748'
  - '2245082750'
  - '2245082777'
  - '2245083013'
  - '2245083071'
  - '2246310117'
  - '2246310122'
  - '2246465314'
  - '2246465343'
  - '2246465347'
  - '2246465351'
  - '2246465360'
  - '2246465365'
  - '2440548742'
  - '2440548796'
  - '344890309'
  - '344890457'
  - '344890541'
  - '344890542'
  - '3661921555'
  - '386431204'
  - '386432221'
  - '4137734218'
  - '4161412300'
  - '4161457092'
  - '4161457099'
  - '4161457100'
  - '4162497498'
  - '4162497519'
  - '5424258008'
  - '5430804028'
  - '5458429249'
  - '5458429260'
  - '5458429287'
  - '5458747513'
  - '5458748725'
  - '5518334407'
  - '5518334411'
  - '5518339345'
  - '5518339352'
  - '5518339354'
  - '6072356072'
  - '6609081696'
  - '6609500419'
  - '6609500420'
  - '6609753291'
  - '6609753292'
  - '6688263217'
  - '6691178209'
  - '7363602547'
  - '7365818056'
  - '7365923716'
  - '7365923717'
  - '7365923719'
  - '7366702073'
  - '7366702075'
  - '7537700039'
  - '7540597141'
  - '7658543134'
  - '7658543142'
  - '7701850136'
  - '7728961745'
  - '8230345921'
  - '9171129215'
  - '9632889098'
  - '9685155700'
  - '968909439'
  - '9771241951'
  - '9869648465'
  - '9992119461'
  - '9992119472'
  - cluster_10261850246_2245082387
  - cluster_11056009669_11056009671
  - cluster_11072489262_4161412293
  - cluster_11182692495_7365923724
  - cluster_11337331273_2245082867
  - cluster_12518863063_4162497494
  - cluster_13312982641_2245082781
  - cluster_1646118610_5458429002
  - cluster_2245082187_4161412282
  - cluster_2245082210_5458428991
  - cluster_2245082219_2245082227
  - cluster_2245082244_2245082249
  - cluster_2245082332_5458428988
  - cluster_2245082368_2245082376
  - cluster_2245082393_2245082423_4233655598
  - cluster_2245082513_4161319752
  - cluster_344890761_6177994518
  - cluster_344890780_5458429001
  - cluster_3803045263_9632917621_9861788790
  - cluster_4161457091_5458428998
  - cluster_5518339350_5518339351
  - joinedS_5458429287_9869648471_9869648479
  - joinedS_9869648476_cluster_10765731565_5458747520_5458748724
  model_save_path: saved_models/universal_model.pth
  log_file: training_logs.json
  enable_patience: true
  patience_epochs: 20
  min_reward_delta: 0.05
